# Generated by Django 5.0.4 on 2024-05-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('costo', models.IntegerField()),
                ('ganancia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('costo', models.IntegerField()),
                ('ganancia', models.IntegerField()),
                ('img', models.ImageField(unique=True, upload_to='C:\\Users\\Little\\ Thing\\Documents\\pizzamoji\\static\\')),
            ],
        ),
    ]
