# Generated by Django 5.0.4 on 2024-05-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_ganancia_ingredientes_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.ImageField(unique=True, upload_to='C:\\Users\\Little Thing\\Documents\\pizzamoji\\static\\'),
        ),
    ]
