# Generated by Django 5.0.4 on 2024-05-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_producto_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.ImageField(null=True, unique=True, upload_to='C:\\Users\\Little Thing\\Documents\\pizzamoji\\static\\'),
        ),
    ]
