# Generated by Django 5.0.4 on 2024-05-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_producto_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientes',
            name='creado',
            field=models.DateField(auto_now=True),
        ),
    ]
