# Generated by Django 5.0.4 on 2024-05-20 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ingredientes_creado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredientes',
            new_name='Ingrediente',
        ),
    ]
